version: "3.9"
services:
  transform-db:
    container_name: transformation
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_DB=transformation
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - '5432'
    ports:
      - '5432:5432'
    networks:
      - hocsnet
  replica-db:
    container_name: replica
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_DB=replica
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - '5433'
    ports:
      - '5433:5432' # not sure if porting is done correctly.
    command: -p 5433
    volumes:
      - dbreplica:/var/lib/postgressql/data
      - ./dbreplica/001-init.sql:/docker-entrypoint-initdb.d/001-init_db.sql
      - ./dbreplica/002-mpam_seed_data.sql:/docker-entrypoint-initdb.d/002-mpam_seed_data.sql
    networks:
      - hocsnet
  etl-process:
    container_name: etl-process
    build: .
    environment:
      - transformation_db_host=transform-db
      - transformation_db_name=transformation
      - transformation_db_endpoint=transform-db
      - transformation_db_password=postgres
      - transformation_db_username=postgres
      - transformation_db_port=5432
      - transformation_db_resource=postgres
      - replica_db_host=replica-db
      - replica_db_name=replica
      - replica_db_username=postgres
      - replica_db_password=postgres
      - replica_db_schema=replica
      - replica_db_port=5433
    depends_on:
      transform-db:
        condition: service_started
      replica-db:
        condition: service_started
    links:
      - transform-db
      - replica-db
    networks:
      - hocsnet

volumes:
  dbtransform:
    driver: local
  dbreplica:
    driver: local

networks:
  hocsnet:
    name: hocsnet
