---
deployment:
  annotations:
    downscaler/downtime: 'Mon-Sun 00:00-05:00 Europe/London,Mon-Sun 23:00-24:00 Europe/London'
app:
  env:
  - name: clientside
    value: "1"
  resources:
    limits:
      cpu: 1000m
      memory: 768Mi
    requests:
      cpu: 200m
      memory: 768Mi