---
deployment:
  annotations:
    downscaler/downtime: 'Mon-Sun 00:00-05:00 Europe/London,Mon-Sun 23:00-24:00 Europe/London'
app:
  env:
  - name: clientside
    value: "1"
  - name: transformation_db_name
    valueFrom:
      secretKeyRef:
        name: cs-mi-dev-transformation-rds
        key: db_name
        optional: false
  - name: transformation_db_host
    valueFrom:
      secretKeyRef:
        name: cs-mi-dev-transformation-rds
        key: endpoint
        optional: false
  - name: transformation_db_password
    valueFrom:
      secretKeyRef:
        name: cs-mi-dev-transformation-rds
        key: password
        optional: false
  - name: transformation_db_username
    valueFrom:
      secretKeyRef:
        name: cs-mi-dev-transformation-rds
        key: username
        optional: false
  - name: transformation_db_port
    valueFrom:
      secretKeyRef:
        name: cs-mi-dev-transformation-rds
        key: port
        optional: false
  - name: transformation_db_resource
    valueFrom:
      secretKeyRef:
        name: cs-mi-dev-transformation-rds
        key: resource_id
        optional: false
  - name: replica_db_host
    valueFrom:
      secretKeyRef:
        name: cs-mi-dev-rds
        key: host
        optional: false
  - name: replica_db_name
    valueFrom:
      secretKeyRef:
        name: cs-mi-dev-rds
        key: name
        optional: false
  - name: replica_db_username
    valueFrom:
      secretKeyRef:
        name: cs-mi-dev-rds
        key: user_name
        optional: false
  - name: replica_db_password
    valueFrom:
      secretKeyRef:
        name: cs-mi-dev-rds
        key: password
        optional: false
  - name: replica_db_schema
    valueFrom:
      secretKeyRef:
        name: cs-mi-dev-rds
        key: schema_name
        optional: false
  - name: replica_db_port
    valueFrom:
      secretKeyRef:
        name: cs-mi-dev-rds
        key: port
        optional: false
  resources:
    limits:
      cpu: 1000m
      memory: 768Mi
    requests:
      cpu: 200m
      memory: 768Mi