transformation_db:
  target: 'not-prod'
  outputs:
    not-prod:
      type: postgres
      host: "{{ env_var('transformation_db_host') }}"
      port: "{{ env_var('transformation_db_port') | as_number }}" # need to get it as an environment variable
      dbname: "{{ env_var('transformation_db_name') }}"
      schema: public
      threads: 1
      user: "{{ env_var('transformation_db_username') }}"
      password: "{{ env_var('transformation_db_password') }}"
