version: 2

sources:
  - name: decs_raw
    schema: public
    description: Raw decs data
    tables:
      - name: audit_data
        columns:
          - name: id
            description: Primary key
          - name: case_uuid
            description: Primary unique key of the
          - name: allocations
