version: 2

sources:
  - name: transformation
    description: Raw decs data
    tables:
      - name: audit_event
        columns:
          - name: id
            description: Primary key
          - name: case_uuid
            description: Primary unique key of the
          - name: allocations
