name: 'Docker Build and push job image'
on:
  pull_request:
    types: [ closed ]

jobs:
  build-and-push:
    uses: UKHomeOffice/hocs-github-actions/.github/workflows/docker-build-tag.yml@v2
    with:
      images: 'quay.io/ukhomeofficedigital/hocs-mi-transformation'
    secrets: inherit